function [S] = gui_component_layout_main(S)

S.fh(1) = figure('units','pixels',...
    'position',[200 650 850 250],...
    'menubar','none',...
    'name','simulation of tdoa location',...
    'numbertitle','off',...
    'resize','off',...
    'closerequestfcn',{@fh_main_crfcn});
S.txmain = uicontrol('units','pixels',...
    'style','text',...
    'unit','pix',...
    'position',[200 190 450 25],...
    'string','Radio Emitter Location using TDOA Sensors',...
    'fontweight','bold',...
    'backgroundcolor',get(S.fh(1),'color'), ...
    'fontsize',15, ...
    'foregroundcolor', 'b');
S.bg = uibuttongroup('units','pix',...
    'pos',[20 70 810 90]);
S.rd(1) = uicontrol(S.bg,...
    'style','rad',...
    'unit','pix',...
    'position',[20 50 130 30],...
    'tooltipstring', sprintf('simulate tdoa location when sensor fixed'), ...
    'fontweight','bold',...
    'string','sensor fixed');

% S.SEL = 1;  % The selected object property of S.bg
% S.SEL_old = 1;

S.rd(2) = uicontrol(S.bg,...
    'style','rad',...
    'unit','pix',...
    'position',[20 10 130 30],...
    'tooltipstring', 'simulate tdoa location when target fixed at [0,0]', ...
    'fontweight','bold',...
    'string','target fixed');
S.rd(3) = uicontrol(S.bg,...
    'style','rad',...
    'unit','pix',...
    'position',[220 50 130 30],...
    'tooltipstring', ...
    sprintf('how location error is varied with\ntarget position and sensor length/shape?'), ...
    'fontweight','bold',...
    'string','batch sensor fixed');
S.rd(4) = uicontrol(S.bg,...
    'style','rad',...
    'unit','pix',...
    'position',[220 10 130 30],...
    'tooltipstring', ...
    sprintf('how location error is varied with\nsensor length, location method, snr?'), ...
    'fontweight','bold',...
    'string','batch target fixed');
S.rd(5) = uicontrol(S.bg,...
    'style','rad',...
    'unit','pix',...
    'position',[420 50 130 30],...
    'tooltipstring', ...
    sprintf('how location error is varied with\ntarget signal bandwidth, correlation length, snr?'), ...
    'fontweight','bold',...
    'string','batch bw corr snr');
S.rd(6) = uicontrol(S.bg,...
    'style','rad',...
    'unit','pix',...
    'position',[420 10 130 30],...
    'tooltipstring','plot result of batch_simulate_tdoa_target_fixed.m', ...
    'fontweight','bold',...
    'string','plot target fixed');
S.rd(7) = uicontrol(S.bg,...
    'style','rad',...
    'unit','pix',...
    'position',[620 50 130 30],...
    'tooltipstring','plot result of batch_simulate_tdoa_sensor_fixed.m', ...
    'fontweight','bold',...
    'string','plot sensor fixed');
S.rd(8) = uicontrol(S.bg,...
    'style','rad',...
    'unit','pix',...
    'position',[620 10 130 30],...
    'tooltipstring','plot result of batch_simulate_tdoa_bw_corr_snr.m', ...
    'fontweight','bold',...
    'string','plot bw corr snr');
S.pb(1) = uicontrol('style','push',...
    'unit','pix',...
    'position',[355 20 150 30],...
    'fontweight','bold',...
    'string','input parameters',...
    'callback',{@pb_input_param_call});
S.fm(1) = uimenu(S.fh(1),...
    'label','sensor position',...
    'enable','on');
S.fm(2) = uimenu(S.fm(1),...
    'label','load',...
    'callback',{@fm_load_sensor_position_call, S.fh(1)},...
    'enable','on');
S.fm(3) = uimenu(S.fm(1),...
    'label','show',...
    'callback',{@fm_show_sensor_position_call, S.fh(1)},...
    'enable','on');
S.fm(4) = uimenu(S.fh(1),...
    'label','fading parameter',...
    'enable','on');
S.fm(5) = uimenu(S.fm(4),...
    'label','load',...
    'callback',{@fm_load_fading_parameter_call, S.fh(1)},...
    'enable','on');
S.fm(6) = uimenu(S.fm(4),...
    'label','clear',...
    'callback',{@fm_clear_fading_parameter_call, S.fh(1)},...
    'enable','on');
S.fm(7) = uimenu(S.fm(4),...
    'label','show',...
    'callback',{@fm_show_fading_parameter_call, S.fh(1)},...
    'enable','on');
S.fm(8) = uimenu(S.fh(1),...
    'label','target signal',...
    'enable','on');
S.fm(9) = uimenu(S.fm(8),...
    'label','LTE PRS',...
    'callback',{@fm_generate_lte_prs_signal_call, S.fh(1)},...
    'enable','on');
S.fm(10) = uimenu(S.fm(8),...
    'label','422MHz(BW 8.5kHz)',...
    'callback',{@fm_generate_422mhz_signal_call, S.fh(1)},...
    'enable','on');
S.fm(11) = uimenu(S.fh(1),...
    'label','about',...
    'callback',{@fm_about_call},...
    'enable','on');

end

