function [] = gui_populate_sensor_fixed_uicontrol(S)
% ##### making external function result: FAILED!!

% This is where we make the other two figures.
S.fh(2) = figure('units','pixels',...
    'position',[1070 500 350 430],...
    'name','input for sensor fixed',...
    'menubar','none',...
    'numbertitle','off',...
    'resize','off',...
    'closerequestfcn',{@fh_sub_crfcn});

S.tx = uicontrol('units','pixels',...
    'style','text',...
    'unit','pix',...
    'position',[70 385 210 25],...
    'string','input for sensor fixed',...
    'fontweight','bold',...
    'fontsize',10, ...
    'foregroundcolor', 'b', ...
    'backgroundcolor',get(S.fh(2),'color'));

S.ed(1) = uicontrol('units','pixels',...
    'style','edit',...
    'unit','pix',...
    'string', '100', ...
    'position',[170 210 150 25]);
S.tx(2) = uicontrol('units','pixels',...
    'style','text',...
    'unit','pix',...
    'position',[30 205 110 25],...
    'string','trial length',...
    'fontweight','bold',...
    'backgroundcolor',get(S.fh(2),'color'));

S.ed(2) = uicontrol('units','pixels',...
    'style','edit',...
    'unit','pix',...
    'string', '1.5', ...
    'position',[170 245 150 25]);
S.tx(3) = uicontrol('units','pixels',...
    'style','text',...
    'unit','pix',...
    'position',[30 240 110 25],...
    'string','radius ratio',...
    'tooltipstring', 'ratio between target distance and farthest sensor distance from [0,0]', ...
    'fontweight','bold',...
    'backgroundcolor',get(S.fh(2),'color'));

S.ed(3) = uicontrol('units','pixels',...
    'style','edit',...
    'unit','pix',...
    'string', '100', ...
    'position',[170 280 150 25]);
S.tx(4) = uicontrol('units','pixels',...
    'style','text',...
    'unit','pix',...
    'position',[30 275 110 25],...
    'string','y of target position',...
    'fontweight','bold',...
    'backgroundcolor',get(S.fh(2),'color'));

S.ed(4) = uicontrol('units','pixels',...
    'style','edit',...
    'unit','pix',...
    'string', '100', ...
    'position',[170 315 150 25]);
S.tx(5) = uicontrol('units','pixels',...
    'style','text',...
    'unit','pix',...
    'position',[30 310 110 25],...
    'string','x of target position',...
    'fontweight','bold',...
    'backgroundcolor',get(S.fh(2),'color'));

S.ed(5) = uicontrol('units','pixels',...
    'style','edit',...
    'unit','pix',...
    'string', '5', ...
    'position',[170 350 150 25]);
S.tx(6) = uicontrol('units','pixels',...
    'style','text',...
    'unit','pix',...
    'position',[30 345 110 25],...
    'string','SNR in dB',...
    'fontweight','bold',...
    'backgroundcolor',get(S.fh(2),'color'));

S.pp(1) = uicontrol('style','pop',...
    'unit','pix',...
    'position',[170 80 70 30],...
    'string',S.str_subframe_length, ...
    'value',1);
S.tx(7) = uicontrol('units','pixels',...
    'style','text',...
    'unit','pix',...
    'position',[30 80 110 25],...
    'string','subframe length',...
    'fontweight','bold',...
    'backgroundcolor',get(S.fh(2),'color'));

%                     ca = get(S.pp(3), {'string', 'value'});
%                     ndlrb = str2num(ca{1}{ca{2}})
%                     cell_nprsrb = cell(ndlrb, 1);
%                     for n = 1 : ndlrb
%                         cell_nprsrb{n} = num2str(n);
%                     end
%                     S.str_nprsrb = cell_nprsrb;
S.pp(2) = uicontrol('style','pop',...
    'unit','pix',...
    'position',[170 120 70 30],...
    'string',S.str_nprsrb,...
    'value',1);
S.tx(8) = uicontrol('units','pixels',...
    'style','text',...
    'unit','pix',...
    'position',[30 120 110 25],...
    'string','NPRSRB',...
    'tooltipstring', 'Number of PRS Resource Block', ...
    'foregroundcolor', 'r', ...
    'fontweight','bold',...
    'backgroundcolor',get(S.fh(2),'color'));

S.pp(3) = uicontrol('style','pop',...
    'unit','pix',...
    'position',[170 160 70 30],...
    'string',S.str_ndlrb,...
    'value',1);
S.tx(9) = uicontrol('units','pixels',...
    'style','text',...
    'unit','pix',...
    'position',[30 160 110 25],...
    'string','NDLRB',...
    'tooltipstring', 'Number of DownLink Resource Block', ...
    'fontweight','bold',...
    'backgroundcolor',get(S.fh(2),'color'));

S.pb_sensor_fixed = uicontrol('style','push',...
    'unit','pix',...
    'position',[100 20 150 30],...
    'fontweight','bold',...
    'string','run sensor fixed',...
    'callback',{@pb_sensor_fixed_call});

end

