function [S] = gui_component_layout_batch_target_fixed(S)

S.fh(2) = figure('units','pixels',...
    'position',[S.second_fig_pos_left 298 417 552],... % [520 298 417 552]
    'name','input for target fixed',...
    'menubar','none',...
    'numbertitle','off',...
    'resize','off',...
    'closerequestfcn',{@fh_sub_crfcn, S.fh(1)});

S.tx(1) = uicontrol('units','pixels',...
    'style','text',...
    'unit','pix',...
    'position',[90 501 185 19],...
    'string','input for batch target fixed',...
    'fontweight','bold',...
    'fontsize',10, ...
    'foregroundcolor', 'b', ...
    'backgroundcolor',get(S.fh(2),'color'));

S.ed(1) = uicontrol('units','pixels',...
    'style','edit',...
    'unit','pix',...
    'string', '3:7', ...
    'position',[177   405    72    23]);
S.tx(2) = uicontrol('units','pixels',...
    'style','text',...
    'unit','pix',...
    'position',[32 410 128 15],...
    'string','sensor length (vector)',...
    'HorizontalAlignment', 'left', ...
    'fontweight','bold',...
    'backgroundcolor',get(S.fh(2),'color'));

S.ed(2) = uicontrol('units','pixels',...
    'style','edit',...
    'unit','pix',...
    'string', '-10:5:15', ...
    'position',[176 329 72 23]);
S.tx(3) = uicontrol('units','pixels',...
    'style','text',...
    'unit','pix',...
    'position',[32 333 112 15],...
    'string','SNR in dB (vector)',...
    'HorizontalAlignment', 'left', ...
    'fontweight','bold',...
    'backgroundcolor',get(S.fh(2),'color'));

S.ed(3) = uicontrol('units','pixels',...
    'style','edit',...
    'unit','pix',...
    'string', '100', ...
    'position',[176   254    72    23]);
S.tx(4) = uicontrol('units','pixels',...
    'style','text',...
    'unit','pix',...
    'position',[32   258   111    15],...
    'string','trial length',...
    'HorizontalAlignment', 'left', ...
    'fontweight','bold',...
    'backgroundcolor',get(S.fh(2),'color'));

S.pb(2) = uicontrol('style','push',...
    'unit','pix',...
    'position',[115 39 175 23],...
    'fontweight','bold',...
    'string','run batch target fixed',...
    'callback',{@pb_run_batch_target_fixed_call, S.fh(1)});

end
