function [S] = gui_component_layout_target_fixed(S)

S.fh(2) = figure('units','pixels',...
    'position',[S.second_fig_pos_left 298 417 552],... % [520 298 417 552]
    'name','input for target fixed',...
    'menubar','none',...
    'numbertitle','off',...
    'resize','off',...
    'closerequestfcn',{@fh_sub_crfcn, S.fh(1)});

S.tx(1) = uicontrol('units','pixels',...
    'style','text',...
    'unit','pix',...
    'position',[150 502 150 15],...
    'string','input for target fixed',...
    'fontweight','bold',...
    'fontsize',10, ...
    'foregroundcolor', 'b', ...
    'backgroundcolor',get(S.fh(2),'color'));

S.lb(1) = uicontrol('units','pixels',...
    'style','listbox',...
    'unit','pix',...
    'string', {'3', '4', '5', '6', '7'}, ...
    'value', 3, ... % default: index = 3, sensor length = 5
    'position',[176 377 169 75]);
S.tx(2) = uicontrol('units','pixels',...
    'style','text',...
    'unit','pix',...
    'position',[69 410 91 15],...
    'string','sensor length',...
    'HorizontalAlignment', 'left', ...
    'fontweight','bold',...
    'backgroundcolor',get(S.fh(2),'color'));

S.ed(1) = uicontrol('units','pixels',...
    'style','edit',...
    'unit','pix',...
    'string', '5', ...
    'position',[176 329 52 23]);
S.tx(3) = uicontrol('units','pixels',...
    'style','text',...
    'unit','pix',...
    'position',[68 333 77 15],...
    'string','SNR in dB',...
    'HorizontalAlignment', 'left', ...
    'fontweight','bold',...
    'backgroundcolor',get(S.fh(2),'color'));

S.cb(1) = uicontrol('units','pixels',...
    'style','checkbox',...
    'unit','pix',...
    'string', 'sensor 1 is always nearest to target', ...
    'fontweight','bold',...
    'backgroundcolor',get(S.fh(2),'color'), ...
    'value', 0, ...
    'position',[50 279 244 23]);
S.cb(2) = uicontrol('units','pixels',...
    'style','checkbox',...
    'unit','pix',...
    'string', 'use only least square estimator', ...
    'fontweight','bold',...
    'backgroundcolor',get(S.fh(2),'color'), ...
    'value', 0, ...
    'position',[50 229 217 23]);
S.cb(3) = uicontrol('units','pixels',...
    'style','checkbox',...
    'unit','pix',...
    'string', 'plot sensor position & hyperbola curve', ...
    'fontweight','bold',...
    'backgroundcolor',get(S.fh(2),'color'), ...
    'value', 1, ...
    'position',[50 179 257 23]);
S.cb(4) = uicontrol('units','pixels',...
    'style','checkbox',...
    'unit','pix',...
    'string', 'plot target signal & correlation', ...
    'fontweight','bold',...
    'backgroundcolor',get(S.fh(2),'color'), ...
    'value', 0, ...
    'position',[50 129 208 23]);

S.pb(2) = uicontrol('style','push',...
    'unit','pix',...
    'position',[137 39 114 23],...
    'fontweight','bold',...
    'string','run target fixed',...
    'callback',{@pb_run_target_fixed_call, S.fh(1)});

end